# Generated by Django 4.1.1 on 2022-09-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_product_pack_product_pack2_product_pack3'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='pack_selection',
            field=models.IntegerField(default=1),
        ),
    ]
