# Generated by Django 4.1.1 on 2022-10-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_items_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='First_name',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
