# Generated by Django 4.1.1 on 2022-10-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_order_items_user_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
