# Generated by Django 4.1.1 on 2022-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_order_details_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
